### ISSUE TITLE
llvm 设置

### ISSUE THREAD

**Issue by FBIanderson** [leontsui1987/VulDetector#1]
![image](https://user-images.githubusercontent.com/36886315/120923641-3a7c0380-c702-11eb-80b4-683c86c48085.png)

你好，我在配置llvm的时候，并没有找到clang.path文件，在llvm文件目录下
![image](https://user-images.githubusercontent.com/36886315/120923671-5e3f4980-c702-11eb-971f-f6d2d001bcc7.png)

**Comment by leontsui1987** [comment]
The clang.path is in VulDetector/llvm_clang

**Comment by FBIanderson** [comment]
clang.path -> clang.patch
